import { AuthModalProvider } from "@/context/auth-modal-context";
import { ThemeProvider } from "@/provider/theme";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Quiz Forms",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<SessionProvider>
					<ThemeProvider>
						<AuthModalProvider>
							<div className="relative flex flex-col h-screen">{children}</div>
						</AuthModalProvider>
					</ThemeProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
